sudo: required
services:
  - docker

before_install:
  - mvn clean package

script:
  - docker build -t samatlabibulla/smartsport .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push samatlabibulla/smartsport