version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo
    ports:
      - "8091:8080"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"