version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: demo
    ports:
      - "8081:8081"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"