apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartsport-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: smartsport
          image: samatlabibulla/smartsport
          ports:
            - containerPort: 8091